### ISSUE TITLE
build

### ISSUE THREAD

**Issue by ufcpp** [ufcpp-live/UfcppLiveAgenda#35]
.NET 6 Preview 4 と VS 16.11 Preview 1 の話題中心に話すつもりなのでタイトルを「build」だけにすると多少タイトル詐欺感あるもののたぶん「build」タイトルにすると思う。

- https://devblogs.microsoft.com/dotnet/announcing-net-6-preview-4/
- https://devblogs.microsoft.com/dotnet/announcing-net-maui-preview-4/
- https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-4/
- https://devblogs.microsoft.com/dotnet/introducing-net-hot-reload/
- https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview#--visual-studio-2019-version-1611-preview-1-
- https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#16.10.0
- https://docs.microsoft.com/ja-jp/dotnet/core/extensions/logger-message-generator

Hot Reload の話中心になるかも。
あと、LINQ の By 系メソッドと Chunk、DateOnly, TimeOnly, ISpanFormattable
`dotnet new web`
C# は更新掛かってなさそう。

[build での C# 10 のデモ](https://mybuild.microsoft.com/sessions/70d379f4-1173-4941-b389-8796152ec7b8?source=speakerdetail)、今現在動くコードがある(リリースブランチにmergeされてないだけな) global using とか file-scoped namespace とかの話より先に、実装全然ない required property とか field とかの話からやってた。

**Comment by ufcpp** [comment]
初見 maui-check、1か所だけ突破できなかった

```txt
 ? Android Emulator Checkup...
  × Android Emulator - x86 - API30 - Google API's not created.

? Recommendation: Create an Android Emulator

! Attempt to fix? [y/n] (y): y
≫ Attempting to fix: Android Emulator
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.AvdManagerCli.run(AvdManagerCli.java:213)
        at com.android.sdklib.tool.AvdManagerCli.main(AvdManagerCli.java:200)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more
Fix applied.  Checking again...
```

**Comment by ufcpp** [comment]
初見 MauiApp1 ビルド時

```
error NU1101: Unable to find package Microsoft.Maui.Controls.Compatibility. No packages exist with this id in source(s): local, Microsoft Visual Studio Offline Packages, nuget.org
error NU1101: Unable to find package Microsoft.Maui. No packages exist with this id in source(s): local, Microsoft Visual Studio Offline Packages, nuget.org
error NU1101: Unable to find package Microsoft.Maui.Resizetizer. No packages exist with this id in source(s): local, Microsoft Visual Studio Offline Packages, nuget.org
```

**Comment by ufcpp** [comment]
Windows 再起動でも解決してない。

**Comment by ufcpp-live** [comment]
System.Runtime.CompilerServices.InterpolatedStringBuilder
//DefaultInterpolatedStringHandler にリネームされるの確定済み。

**Comment by ufcpp-live** [comment]
```cs
// 既存の string interpolation に関しては…
IFormattable f = $"{1}";
// パターンベースではない。
// 常に
// System.Runtime.CompilerServices.FormattableStringFactory
// が生成されたはず。
// カスタマイズ性なし。
// かつ、FormattableString がボックス化起こしまくる。
```

**Comment by ufcpp-live** [comment]
Date 問題。

![image](https://user-images.githubusercontent.com/62176519/120104578-0ba8df00-c190-11eb-9e1e-2c6be58c5bef.png)

**Comment by ufcpp-live** [comment]
```cs
//TimeOfDay
TimeOnly tod = new TimeOnly(DateTime.Now.TimeOfDay.Ticks);
Console.WriteLine(tod); //ToString 分までしか出さないんだ…
Console.WriteLine(tod.Second);
Console.WriteLine($"{tod:HH:mm:ss.ffff}"); // 時:分:秒
//Console.WriteLine($"{tod:yyyy:MM}"); // さすがに例外

var dt = default(DateOnly).ToDateTime(default); // local time
DateTimeOffset dto = dt; // +9 たる我々はここで例外

// パット見、ToDateTime 内の問題っぽい。
// DateOnly 自体はオフセット関係ないと思いたい。
```

**Comment by ufcpp-live** [comment]
以下のコードを生成してしまう source generator は書けちゃう…

```cs
global using Date = System.DateOnly;
```

**Comment by ufcpp-live** [comment]
```cs
using System;
using System.Linq;

var items = new[]
{
    (4, "b"),
    (3, "c"),
    (1, "a"),
    (5, "d"),
    (2, "e"),
};

// 意外なことに、要望 issue が立ってたの２年程度前。
// ２年で入ったなら早い方なので…
Console.WriteLine(items.MinBy(x => x.Item1));

// 昔から必要としてた人は Ix 入れてたのかな…
```

**Comment by ufcpp-live** [comment]
```cs
using System;
using System.Linq;

var items = new[]
{
    (4, "b"),
    (3, "c"),
    (1, "a3"),
    (1, "a2"),
    (1, "a5"),
    (5, "d"),
    (2, "e"),
};

// 最初に見つかった1個。
Console.WriteLine(items.MinBy(x => x.Item1));
```

**Comment by ufcpp-live** [comment]
```cs
using System;
using System.Linq;

var items = new[] { 1, 2, 3, 4, 5, 6, };

foreach (var chunk in items.Chunk(2))
{
    Console.WriteLine(string.Join(", ", chunk));
}

// C# 8 で items[1..^1] って書いてくれる人少なかったらしいんだけど…
// LINQ が Index/Range に対応したらさすがにみんな使ってくれるかな…
foreach (var item in items.Take(1..^1))
{
    Console.WriteLine(item);
}

int m(int x)
{
    switch (x)
    {
        case 0: return 1;
        case 1: return 2;
        case 2: return 0;
        default: return -1;
    }
}
```

**Comment by ufcpp-live** [comment]
```cs
using System;
using System.Linq;

var items = new[] { 0, 1, 2, 3, 4, 5, 6, };

var x = items.FirstOrDefault(x => x > 10, -1);

Console.WriteLine(x); // 今までだと 0 しか返ってこなくて困ってた。
// Cast<int?>() 書きたくねぇ…
```

**Comment by ufcpp-live** [comment]
```cs
using System.Linq;

var items = new[] { 0, 1, 2, 3, 4, 5, 6, };

// 昔
foreach (var (x, y) in items.Zip(items, (x, y) => (x, y))) { }

// .NET 5
foreach (var (x, y) in items.Zip(items)) { }

// .NET 6
foreach (var (x, y, z) in items.Zip(items, items)) { }

// .NET 7 で！？
// 16引数まで！？
```

**Comment by ufcpp-live** [comment]
![image](https://user-images.githubusercontent.com/62176519/120109167-42d4bb80-c1a3-11eb-88cf-db4537d97f57.png)

**Comment by ufcpp-live** [comment]
```cs
using System;

var w = 1;
var x = 2;
var y = 1.2;
var z = 123;

void realloc(ref Span<char> buffer)
{
    var newBuffer = new char[buffer.Length * 2];
    buffer.CopyTo(newBuffer);
    buffer = newBuffer;
}

string m(int estimatedCapacity)
{
    Span<char> buffer = estimatedCapacity <= 512
        ? stackalloc char[estimatedCapacity]
        : new char[estimatedCapacity];

    int written = 0;
    int totalWritten = 0;
    var p = buffer;
    if (!w.TryFormat(p, out written)) realloc(ref buffer); // TryFormat やりなおしも要る
    p = p[written..];
    totalWritten += written;
    if (!x.TryFormat(p, out written)) realloc(ref buffer);
    p = p[written..];
    totalWritten += written;
    if (!y.TryFormat(p, out written)) realloc(ref buffer);
    p = p[written..];
    totalWritten += written;
    if (!z.TryFormat(p, out written)) realloc(ref buffer);
    p = p[written..];
    totalWritten += written;

    return buffer.ToString();
}

var s = w.ToString() + x.ToString() + y.ToString() + z.ToString();
Console.WriteLine(s);

//Console.WriteLine(buffer[..totalLen].ToString());
```

**Comment by ufcpp-live** [comment]
MAUI、まだマルチDPI対応さすがにしてなかった。

![image](https://user-images.githubusercontent.com/62176519/120930575-db7db500-c728-11eb-96d3-2dedecff1998.png)
